import type { SettingsSection } from "renderer/stores/settings-state";
import { matchSettings } from "./matcher";

export const SETTING_ITEM_ID = {
	ACCOUNT_PROFILE: "account-profile",
	ACCOUNT_IDENTITY: "account-identity",
	ACCOUNT_USAGE: "account-usage",
	ACCOUNT_SIGNOUT: "account-signout",

	ORGANIZATION_LOGO: "organization-logo",
	ORGANIZATION_NAME: "organization-name",
	ORGANIZATION_SLUG: "organization-slug",
	ORGANIZATION_ID: "organization-id",
	ORGANIZATION_MEMBERS_LIST: "organization-members-list",
	ORGANIZATION_MEMBERS_INVITE: "organization-members-invite",
	ORGANIZATION_MEMBERS_PENDING_INVITATIONS:
		"organization-members-pending-invitations",

	TEAMS_LIST: "teams-list",

	APPEARANCE_THEME: "appearance-theme",
	APPEARANCE_MARKDOWN: "appearance-markdown",
	APPEARANCE_CUSTOM_THEMES: "appearance-custom-themes",
	APPEARANCE_UI_FONT: "appearance-ui-font",
	APPEARANCE_EDITOR_FONT: "appearance-editor-font",
	APPEARANCE_TERMINAL_FONT: "appearance-terminal-font",
	APPEARANCE_ANIMATIONS: "appearance-animations",
	APPEARANCE_GLASS: "appearance-glass",
	APPEARANCE_WALLPAPER: "appearance-wallpaper",
	APPEARANCE_LOADING_SCREEN: "appearance-loading-screen",

	SURFACES_SIDEBAR: "surfaces-sidebar",

	RINGTONES_NOTIFICATION: "ringtones-notification",

	KEYBOARD_SHORTCUTS: "keyboard-shortcuts",
	VOICE_INPUT: "voice-input",
	VOICE_OUTPUT: "voice-output",
	VOICE_ALWAYS_ON_AGENT: "voice-always-on-agent",
	VOICE_AGENT_CONTEXT: "voice-agent-context",
	VOICE_HISTORY: "voice-history",
	BEHAVIOR_CONFIRM_QUIT: "behavior-confirm-quit",
	BEHAVIOR_FILE_OPEN_MODE: "behavior-file-open-mode",
	BEHAVIOR_RESOURCE_MONITOR: "behavior-resource-monitor",
	BEHAVIOR_OPEN_LINKS_IN_APP: "behavior-open-links-in-app",

	GIT_BRANCH_PREFIX: "git-branch-prefix",
	GIT_DELETE_LOCAL_BRANCH: "git-delete-local-branch",
	GIT_WORKTREE_LOCATION: "git-worktree-location",

	AGENTS_ENABLED: "agents-enabled",
	AGENTS_COMMANDS: "agents-commands",
	AGENTS_TASK_PROMPTS: "agents-task-prompts",

	TERMINAL_PRESETS: "terminal-presets",
	TERMINAL_QUICK_ADD: "terminal-quick-add",
	TERMINAL_SESSIONS: "terminal-sessions",
	TERMINAL_LINK_BEHAVIOR: "terminal-link-behavior",

	LINKS_FILE: "links-file",
	LINKS_URL: "links-url",
	LINKS_SIDEBAR_FILE: "links-sidebar-file",

	PUBLIC_SHARES: "public-shares",

	MODELS_ROX: "models-rox",
	MODELS_ANTHROPIC: "models-anthropic",
	MODELS_OPENAI: "models-openai",
	MODELS_GROQ: "models-groq",
	MODELS_GOOGLE: "models-google",
	MODELS_DEEPSEEK: "models-deepseek",
	MODELS_CUSTOM: "models-custom",

	EXPERIMENTAL_V1_MIGRATION: "experimental-v1-migration",
	EXPERIMENTAL_RERUN_ONBOARDING: "experimental-rerun-onboarding",
	EXPERIMENTAL_TEAM_OS: "experimental-team-os",

	INTEGRATIONS_LINEAR: "integrations-linear",
	INTEGRATIONS_GITHUB: "integrations-github",
	INTEGRATIONS_SLACK: "integrations-slack",
	INTEGRATIONS_TELEGRAM: "integrations-telegram",
	INTEGRATIONS_DISCORD: "integrations-discord",
	INTEGRATIONS_NOTION: "integrations-notion",
	INTEGRATIONS_OBSIDIAN: "integrations-obsidian",
	INTEGRATIONS_FIBERY: "integrations-fibery",
	INTEGRATIONS_LARK: "integrations-lark",

	PROJECT_NAME: "project-name",
	PROJECT_PATH: "project-path",
	PROJECT_SCRIPTS: "project-scripts",
	PROJECT_BRANCH_PREFIX: "project-branch-prefix",
	PROJECT_WORKTREE_LOCATION: "project-worktree-location",
	PROJECT_IMPORT_WORKTREES: "project-import-worktrees",
	PROJECT_ENV_VARS: "project-env-vars",

	API_KEYS_LIST: "api-keys-list",
	API_KEYS_GENERATE: "api-keys-generate",

	PERMISSIONS_FULL_DISK_ACCESS: "permissions-full-disk-access",
	PERMISSIONS_ACCESSIBILITY: "permissions-accessibility",
	PERMISSIONS_MICROPHONE: "permissions-microphone",
	PERMISSIONS_APPLE_EVENTS: "permissions-apple-events",
	PERMISSIONS_LOCAL_NETWORK: "permissions-local-network",

	SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY:
		"security-expose-host-service-via-relay",

	HOST_MEMBERS: "host-members",
	HOST_INVITE_MEMBER: "host-invite-member",
	HOST_MEMBER_ROLE: "host-member-role",
	HOST_WORKTREE_LOCATION: "host-worktree-location",
} as const;

export type SettingItemId =
	(typeof SETTING_ITEM_ID)[keyof typeof SETTING_ITEM_ID];

export interface SettingsItem {
	id: SettingItemId;
	section: SettingsSection;
	title: string;
	description: string;
	keywords: string[];
}

/**
 * Which v1/v2 variant of the desktop UI a setting applies to.
 * - "v1": only used by the legacy desktop UI; hide when the user is on v2.
 * - "v2": only meaningful in the v2 desktop UI; hide when the user is on v1.
 * - "shared": applies to both (or is provided by a global/cloud surface).
 *
 * Source of truth for the v1/v2 settings audit. When adding a new setting,
 * pick a variant or it will fail typecheck on the registry below.
 */
export type SettingVariant = "v1" | "v2" | "shared";

export const SETTING_ITEM_VARIANT: Record<SettingItemId, SettingVariant> = {
	[SETTING_ITEM_ID.ACCOUNT_PROFILE]: "shared",
	[SETTING_ITEM_ID.ACCOUNT_IDENTITY]: "shared",
	[SETTING_ITEM_ID.ACCOUNT_USAGE]: "shared",
	[SETTING_ITEM_ID.ACCOUNT_SIGNOUT]: "shared",

	[SETTING_ITEM_ID.ORGANIZATION_LOGO]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_NAME]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_SLUG]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_ID]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_MEMBERS_LIST]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_MEMBERS_INVITE]: "shared",
	[SETTING_ITEM_ID.ORGANIZATION_MEMBERS_PENDING_INVITATIONS]: "shared",

	[SETTING_ITEM_ID.TEAMS_LIST]: "shared",

	[SETTING_ITEM_ID.APPEARANCE_THEME]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_MARKDOWN]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_CUSTOM_THEMES]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_UI_FONT]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_EDITOR_FONT]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_TERMINAL_FONT]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_ANIMATIONS]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_GLASS]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_WALLPAPER]: "shared",
	[SETTING_ITEM_ID.APPEARANCE_LOADING_SCREEN]: "shared",

	[SETTING_ITEM_ID.SURFACES_SIDEBAR]: "shared",

	[SETTING_ITEM_ID.RINGTONES_NOTIFICATION]: "shared",

	[SETTING_ITEM_ID.KEYBOARD_SHORTCUTS]: "shared",
	[SETTING_ITEM_ID.VOICE_INPUT]: "shared",
	[SETTING_ITEM_ID.VOICE_OUTPUT]: "shared",
	[SETTING_ITEM_ID.VOICE_ALWAYS_ON_AGENT]: "shared",
	[SETTING_ITEM_ID.VOICE_AGENT_CONTEXT]: "shared",
	[SETTING_ITEM_ID.VOICE_HISTORY]: "shared",

	[SETTING_ITEM_ID.BEHAVIOR_CONFIRM_QUIT]: "shared",
	[SETTING_ITEM_ID.BEHAVIOR_FILE_OPEN_MODE]: "v1",
	[SETTING_ITEM_ID.BEHAVIOR_RESOURCE_MONITOR]: "shared",
	[SETTING_ITEM_ID.BEHAVIOR_OPEN_LINKS_IN_APP]: "v1",

	// Branch prefix exists in both UIs — v1 `GitSettings`, v2 `V2GitSettings`.
	[SETTING_ITEM_ID.GIT_BRANCH_PREFIX]: "shared",
	[SETTING_ITEM_ID.GIT_DELETE_LOCAL_BRANCH]: "v1",
	[SETTING_ITEM_ID.GIT_WORKTREE_LOCATION]: "shared",

	[SETTING_ITEM_ID.AGENTS_ENABLED]: "shared",
	[SETTING_ITEM_ID.AGENTS_COMMANDS]: "shared",
	[SETTING_ITEM_ID.AGENTS_TASK_PROMPTS]: "shared",

	[SETTING_ITEM_ID.TERMINAL_PRESETS]: "shared",
	[SETTING_ITEM_ID.TERMINAL_QUICK_ADD]: "shared",
	[SETTING_ITEM_ID.TERMINAL_SESSIONS]: "shared",
	[SETTING_ITEM_ID.TERMINAL_LINK_BEHAVIOR]: "v1",

	[SETTING_ITEM_ID.LINKS_FILE]: "v2",
	[SETTING_ITEM_ID.LINKS_URL]: "v2",
	[SETTING_ITEM_ID.LINKS_SIDEBAR_FILE]: "v2",

	[SETTING_ITEM_ID.PUBLIC_SHARES]: "shared",

	[SETTING_ITEM_ID.MODELS_ROX]: "shared",
	[SETTING_ITEM_ID.MODELS_ANTHROPIC]: "shared",
	[SETTING_ITEM_ID.MODELS_OPENAI]: "shared",
	[SETTING_ITEM_ID.MODELS_GROQ]: "shared",
	[SETTING_ITEM_ID.MODELS_GOOGLE]: "shared",
	[SETTING_ITEM_ID.MODELS_DEEPSEEK]: "shared",
	[SETTING_ITEM_ID.MODELS_CUSTOM]: "shared",

	[SETTING_ITEM_ID.EXPERIMENTAL_V1_MIGRATION]: "v2",
	[SETTING_ITEM_ID.EXPERIMENTAL_RERUN_ONBOARDING]: "v2",
	[SETTING_ITEM_ID.EXPERIMENTAL_TEAM_OS]: "shared",

	[SETTING_ITEM_ID.INTEGRATIONS_LINEAR]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_GITHUB]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_SLACK]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_TELEGRAM]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_DISCORD]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_NOTION]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_OBSIDIAN]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_FIBERY]: "shared",
	[SETTING_ITEM_ID.INTEGRATIONS_LARK]: "shared",

	[SETTING_ITEM_ID.PROJECT_NAME]: "shared",
	[SETTING_ITEM_ID.PROJECT_PATH]: "shared",
	[SETTING_ITEM_ID.PROJECT_SCRIPTS]: "v1",
	[SETTING_ITEM_ID.PROJECT_BRANCH_PREFIX]: "v1",
	[SETTING_ITEM_ID.PROJECT_WORKTREE_LOCATION]: "shared",
	[SETTING_ITEM_ID.PROJECT_IMPORT_WORKTREES]: "v1",
	[SETTING_ITEM_ID.PROJECT_ENV_VARS]: "v2",

	[SETTING_ITEM_ID.API_KEYS_LIST]: "shared",
	[SETTING_ITEM_ID.API_KEYS_GENERATE]: "shared",

	[SETTING_ITEM_ID.PERMISSIONS_FULL_DISK_ACCESS]: "shared",
	[SETTING_ITEM_ID.PERMISSIONS_ACCESSIBILITY]: "shared",
	[SETTING_ITEM_ID.PERMISSIONS_MICROPHONE]: "shared",
	[SETTING_ITEM_ID.PERMISSIONS_APPLE_EVENTS]: "shared",
	[SETTING_ITEM_ID.PERMISSIONS_LOCAL_NETWORK]: "shared",

	[SETTING_ITEM_ID.SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY]: "shared",

	[SETTING_ITEM_ID.HOST_MEMBERS]: "shared",
	[SETTING_ITEM_ID.HOST_INVITE_MEMBER]: "shared",
	[SETTING_ITEM_ID.HOST_MEMBER_ROLE]: "shared",
	[SETTING_ITEM_ID.HOST_WORKTREE_LOCATION]: "v2",
};

export function isItemAllowedForVariant(
	itemId: SettingItemId,
	isV2: boolean,
): boolean {
	const variant = SETTING_ITEM_VARIANT[itemId];
	if (variant === "shared") return true;
	return isV2 ? variant === "v2" : variant === "v1";
}

export const SETTINGS_ITEMS: SettingsItem[] = [
	{
		id: SETTING_ITEM_ID.ACCOUNT_PROFILE,
		section: "account",
		title: "Профиль",
		description: "Информация вашего профиля",
		keywords: [
			"account",
			"name",
			"email",
			"avatar",
			"user",
			"profile",
			"picture",
			"photo",
			"me",
			"профиль",
			"аккаунт",
			"учётная запись",
			"имя",
			"почта",
			"электронная почта",
			"аватар",
			"фото",
			"пользователь",
			"я",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_IDENTITY,
		section: "account",
		title: "Идентичность",
		description: "Привязанные аккаунты и имя пользователя",
		keywords: [
			"identity",
			"username",
			"handle",
			"nickname",
			"connected accounts",
			"linked accounts",
			"github",
			"telegram",
			"twitter",
			"x",
			"oauth",
			"provider",
			"идентичность",
			"имя пользователя",
			"никнейм",
			"привязанные аккаунты",
			"связанные аккаунты",
			"гитхаб",
			"телеграм",
			"провайдер",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_SIGNOUT,
		section: "account",
		title: "Выйти",
		description: "Выйти из вашего аккаунта",
		keywords: [
			"account",
			"sign out",
			"logout",
			"log out",
			"disconnect",
			"leave",
			"выйти",
			"выход",
			"аккаунт",
			"учётная запись",
			"отключиться",
			"завершить сеанс",
			"покинуть",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_USAGE,
		section: "account",
		title: "Баланс и сессии",
		description: "Детализация баланса, расходов, моделей и чат-сессий",
		keywords: [
			"account",
			"usage",
			"balance",
			"sessions",
			"billing",
			"tokens",
			"models",
			"cost",
			"rox",
			"ledger",
			"аккаунт",
			"баланс",
			"сессии",
			"расходы",
			"токены",
			"модели",
			"стоимость",
			"история",
			"детализация",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_LOGO,
		section: "organization",
		title: "Логотип организации",
		description: "Загрузка и управление логотипом вашей организации",
		keywords: [
			"organization",
			"logo",
			"image",
			"branding",
			"upload",
			"icon",
			"picture",
			"avatar",
			"организация",
			"логотип",
			"изображение",
			"брендинг",
			"загрузка",
			"иконка",
			"картинка",
			"аватар",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_NAME,
		section: "organization",
		title: "Название организации",
		description: "Изменение отображаемого названия вашей организации",
		keywords: [
			"organization",
			"name",
			"rename",
			"title",
			"company",
			"team name",
			"организация",
			"название",
			"имя",
			"переименовать",
			"заголовок",
			"компания",
			"название команды",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_SLUG,
		section: "organization",
		title: "Слаг организации",
		description: "Уникальный идентификатор вашей организации",
		keywords: [
			"organization",
			"slug",
			"url",
			"identifier",
			"subdomain",
			"link",
			"unique",
			"организация",
			"слаг",
			"идентификатор",
			"поддомен",
			"ссылка",
			"уникальный",
			"адрес",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_ID,
		section: "organization",
		title: "Идентификатор организации",
		description: "Уникальный идентификатор вашей организации",
		keywords: [
			"organization",
			"id",
			"identifier",
			"uuid",
			"unique",
			"copy",
			"api",
			"организация",
			"идентификатор",
			"уникальный",
			"копировать",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_LIST,
		section: "organization",
		title: "Участники команды",
		description: "Просмотр и управление участниками команды и их ролями",
		keywords: [
			"organization",
			"members",
			"team",
			"users",
			"roles",
			"people",
			"collaborators",
			"permissions",
			"access",
			"admin",
			"owner",
			"организация",
			"участники",
			"команда",
			"пользователи",
			"роли",
			"люди",
			"сотрудники",
			"права",
			"доступ",
			"администратор",
			"владелец",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_INVITE,
		section: "organization",
		title: "Пригласить участников",
		description: "Приглашение новых участников в вашу организацию",
		keywords: [
			"organization",
			"members",
			"invite",
			"add",
			"new member",
			"team",
			"share",
			"collaborate",
			"email",
			"send invite",
			"организация",
			"участники",
			"пригласить",
			"добавить",
			"новый участник",
			"команда",
			"поделиться",
			"совместная работа",
			"почта",
			"отправить приглашение",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_PENDING_INVITATIONS,
		section: "organization",
		title: "Ожидающие приглашения",
		description: "Просмотр и управление ожидающими приглашениями в организацию",
		keywords: [
			"organization",
			"members",
			"invite",
			"invitation",
			"pending",
			"team",
			"waiting",
			"sent",
			"cancel",
			"resend",
			"email",
			"организация",
			"участники",
			"пригласить",
			"приглашение",
			"ожидающие",
			"команда",
			"в ожидании",
			"отправленные",
			"отменить",
			"отправить повторно",
			"почта",
		],
	},
	{
		id: SETTING_ITEM_ID.TEAMS_LIST,
		section: "teams",
		title: "Команды",
		description:
			"Создание, переименование и удаление команд в вашей организации",
		keywords: [
			"teams",
			"team",
			"group",
			"create team",
			"rename team",
			"delete team",
			"organize",
			"команды",
			"команда",
			"группа",
			"создать команду",
			"переименовать команду",
			"удалить команду",
			"организовать",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_THEME,
		section: "appearance",
		title: "Тема",
		description: "Выберите вашу тему",
		keywords: [
			"appearance",
			"theme",
			"dark",
			"light",
			"dark mode",
			"light mode",
			"colors",
			"night",
			"system",
			"visual",
			"внешний вид",
			"оформление",
			"тема",
			"тёмная",
			"светлая",
			"тёмная тема",
			"светлая тема",
			"цвета",
			"ночная",
			"системная",
			"визуальное",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_MARKDOWN,
		section: "appearance",
		title: "Стиль Markdown",
		description: "Стиль отображения файлов markdown",
		keywords: [
			"appearance",
			"markdown",
			"style",
			"tufte",
			"rendering",
			"preview",
			"format",
			"display",
			"md",
			"readme",
			"внешний вид",
			"оформление",
			"маркдаун",
			"стиль",
			"отрисовка",
			"предпросмотр",
			"формат",
			"отображение",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_CUSTOM_THEMES,
		section: "appearance",
		title: "Пользовательские темы",
		description: "Импорт пользовательских файлов тем",
		keywords: [
			"appearance",
			"custom",
			"themes",
			"import",
			"json",
			"color scheme",
			"upload",
			"personalize",
			"customize",
			"внешний вид",
			"оформление",
			"пользовательские",
			"темы",
			"импорт",
			"цветовая схема",
			"загрузка",
			"персонализация",
			"настроить",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_UI_FONT,
		section: "appearance",
		title: "Шрифт интерфейса",
		description: "Шрифт, используемый в навигации, настройках и app chrome",
		keywords: [
			"appearance",
			"font",
			"ui font",
			"interface font",
			"family",
			"size",
			"chrome",
			"navigation",
			"typography",
			"custom",
			"внешний вид",
			"оформление",
			"шрифт",
			"гарнитура",
			"размер",
			"интерфейс",
			"навигация",
			"типографика",
			"пользовательский",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_EDITOR_FONT,
		section: "appearance",
		title: "Шрифт редактора",
		description:
			"Шрифт, используемый в просмотре изменений и редакторах файлов",
		keywords: [
			"appearance",
			"font",
			"editor font",
			"family",
			"size",
			"editor",
			"diff",
			"mono",
			"monospace",
			"typography",
			"custom",
			"внешний вид",
			"оформление",
			"шрифт",
			"гарнитура",
			"размер",
			"редактор",
			"различия",
			"изменения",
			"моноширинный",
			"типографика",
			"пользовательский",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_TERMINAL_FONT,
		section: "appearance",
		title: "Шрифт терминала",
		description: "Шрифт, используемый в панелях терминала",
		keywords: [
			"appearance",
			"font",
			"terminal font",
			"family",
			"size",
			"terminal",
			"mono",
			"monospace",
			"typography",
			"custom",
			"nerd",
			"внешний вид",
			"оформление",
			"шрифт",
			"гарнитура",
			"размер",
			"терминал",
			"моноширинный",
			"типографика",
			"пользовательский",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_ANIMATIONS,
		section: "appearance",
		title: "Анимации",
		description: "Управление количеством движения в приложении",
		keywords: [
			"appearance",
			"animation",
			"animations",
			"motion",
			"reduced motion",
			"accessibility",
			"a11y",
			"full",
			"essential",
			"off",
			"performance",
			"внешний вид",
			"оформление",
			"анимация",
			"анимации",
			"движение",
			"уменьшенное движение",
			"доступность",
			"полные",
			"основные",
			"выключить",
			"производительность",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_GLASS,
		section: "appearance",
		title: "Остекление",
		description: "Полупрозрачные панели и эффект размытия окна",
		keywords: [
			"appearance",
			"glass",
			"vibrancy",
			"blur",
			"transparency",
			"translucent",
			"opacity",
			"acrylic",
			"frosted",
			"внешний вид",
			"оформление",
			"остекление",
			"стекло",
			"стеклянные поверхности",
			"размытие",
			"прозрачность",
			"прозрачный дизайн",
			"полупрозрачность",
			"непрозрачность",
			"акрил",
			"матовое",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_WALLPAPER,
		section: "appearance",
		title: "Обои",
		description: "Фоновое изображение с авто-сменой",
		keywords: [
			"appearance",
			"wallpaper",
			"background",
			"image",
			"gradient",
			"rotate",
			"auto rotate",
			"interval",
			"backdrop",
			"внешний вид",
			"оформление",
			"обои",
			"фон",
			"фоновое изображение",
			"градиент",
			"смена",
			"авто-смена",
			"интервал",
			"задний фон",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_LOADING_SCREEN,
		section: "appearance",
		title: "Экран ожидания",
		description: "Мотивационная цитата вместо спиннера при долгих переходах",
		keywords: [
			"appearance",
			"loading",
			"loading screen",
			"quote",
			"quotes",
			"spinner",
			"motivation",
			"transition",
			"focus",
			"внешний вид",
			"оформление",
			"экран ожидания",
			"загрузка",
			"цитата",
			"цитаты",
			"спиннер",
			"мотивация",
			"переход",
			"фокус",
			"заставка",
		],
	},
	{
		id: SETTING_ITEM_ID.SURFACES_SIDEBAR,
		section: "surfaces",
		title: "Поверхности",
		description: "Показ и скрытие разделов боковой панели",
		keywords: [
			"surfaces",
			"surface",
			"sidebar",
			"dashboard",
			"visibility",
			"show",
			"hide",
			"mail",
			"drive",
			"calendar",
			"notes",
			"inbox",
			"journal",
			"memory",
			"поверхности",
			"поверхность",
			"боковая панель",
			"панель",
			"видимость",
			"показать",
			"скрыть",
			"почта",
			"диск",
			"календарь",
			"заметки",
			"входящие",
			"журнал",
			"память",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_NOTIFICATION,
		section: "ringtones",
		title: "Звук уведомлений",
		description: "Выберите звук уведомления для завершённых задач",
		keywords: [
			"notifications",
			"notification",
			"sound",
			"ringtone",
			"audio",
			"alert",
			"bell",
			"tone",
			"complete",
			"done",
			"finished",
			"chime",
			"mute",
			"volume",
			"уведомления",
			"уведомление",
			"звук",
			"мелодия",
			"рингтон",
			"аудио",
			"оповещение",
			"сигнал",
			"завершено",
			"готово",
			"беззвучно",
			"громкость",
		],
	},
	{
		id: SETTING_ITEM_ID.KEYBOARD_SHORTCUTS,
		section: "keyboard",
		title: "Горячие клавиши",
		description: "Просмотр и настройка горячих клавиш",
		keywords: [
			"keyboard",
			"shortcuts",
			"hotkeys",
			"keys",
			"bindings",
			"keybindings",
			"commands",
			"ctrl",
			"cmd",
			"alt",
			"customize",
			"клавиатура",
			"горячие клавиши",
			"сочетания клавиш",
			"клавиши",
			"привязки",
			"команды",
			"настроить",
		],
	},
	{
		id: SETTING_ITEM_ID.VOICE_INPUT,
		section: "voice",
		title: "Голосовой ввод",
		description:
			"Кнопка микрофона в prompt input и горячая клавиша для диктовки промптов",
		keywords: [
			"voice",
			"dictation",
			"microphone",
			"mic",
			"speech",
			"recognition",
			"input",
			"prompt",
			"push-to-talk",
			"голос",
			"диктовка",
			"микрофон",
			"распознавание",
			"ввод",
			"промпт",
			"речь",
		],
	},
	{
		id: SETTING_ITEM_ID.VOICE_OUTPUT,
		section: "voice",
		title: "Голос озвучивания",
		description:
			"Голос для кнопки «Прослушать» под ответами агента; работает через edge-TTS",
		keywords: [
			"voice",
			"tts",
			"text-to-speech",
			"listen",
			"audio",
			"speaker",
			"edge-tts",
			"speech",
			"голос",
			"озвучивание",
			"прослушать",
			"аудио",
			"динамик",
			"синтез речи",
		],
	},
	{
		id: SETTING_ITEM_ID.VOICE_ALWAYS_ON_AGENT,
		section: "voice",
		title: "Фоновый агент",
		description:
			"Опциональное постоянное прослушивание для проактивной помощи с видимым индикатором записи",
		keywords: [
			"voice",
			"always-on",
			"ambient",
			"background",
			"agent",
			"recording",
			"listening",
			"privacy",
			"голос",
			"фоновый агент",
			"фон",
			"постоянное прослушивание",
			"запись",
			"индикатор записи",
			"приватность",
		],
	},
	{
		id: SETTING_ITEM_ID.VOICE_AGENT_CONTEXT,
		section: "voice",
		title: "Контекст для агента",
		description:
			"Термины, имена, проекты и предпочтения, которые помогают точнее распознавать диктовку",
		keywords: [
			"voice",
			"context",
			"prompt",
			"persona",
			"terms",
			"names",
			"projects",
			"preferences",
			"recognition",
			"голос",
			"контекст",
			"персона",
			"термины",
			"имена",
			"проекты",
			"предпочтения",
			"распознавание",
		],
	},
	{
		id: SETTING_ITEM_ID.VOICE_HISTORY,
		section: "voice",
		title: "История диктовки",
		description: "Надиктованные промпты и их расшифровки",
		keywords: [
			"voice",
			"history",
			"transcript",
			"transcripts",
			"dictation",
			"prompt",
			"speech",
			"голос",
			"история",
			"расшифровка",
			"транскрипт",
			"диктовка",
			"промпт",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_CONFIRM_QUIT,
		section: "behavior",
		title: "Подтверждать перед выходом",
		description: "Показывать диалог подтверждения при выходе из приложения",
		keywords: [
			"features",
			"confirm",
			"quit",
			"quitting",
			"exit",
			"close",
			"dialog",
			"warning",
			"prompt",
			"unsaved",
			"поведение",
			"подтвердить",
			"выход",
			"выйти",
			"закрыть",
			"диалог",
			"предупреждение",
			"запрос",
			"несохранённое",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_DELETE_LOCAL_BRANCH,
		section: "git",
		title: "Удалять локальную ветку при удалении рабочего пространства",
		description:
			"Также удалять локальную ветку git при удалении рабочего пространства worktree",
		keywords: [
			"git",
			"delete",
			"branch",
			"local",
			"worktree",
			"workspace",
			"remove",
			"cleanup",
			"гит",
			"удалить",
			"ветка",
			"локальная",
			"рабочее пространство",
			"убрать",
			"очистка",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_BRANCH_PREFIX,
		section: "git",
		title: "Префикс ветки",
		description: "Префикс по умолчанию для имён новых веток",
		keywords: [
			"git",
			"branch",
			"prefix",
			"naming",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
			"гит",
			"ветка",
			"префикс",
			"именование",
			"автор",
			"имя пользователя",
			"пользовательский",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_FILE_OPEN_MODE,
		section: "behavior",
		title: "Режим открытия файлов",
		description:
			"Выберите, как открываются файлы при клике в дереве файлов или просмотре изменений",
		keywords: [
			"file",
			"open",
			"mode",
			"split",
			"pane",
			"tab",
			"new tab",
			"split pane",
			"viewer",
			"behavior",
			"файл",
			"открыть",
			"режим",
			"разделение",
			"панель",
			"вкладка",
			"новая вкладка",
			"разделённая панель",
			"просмотр",
			"поведение",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_RESOURCE_MONITOR,
		section: "behavior",
		title: "Монитор ресурсов",
		description:
			"Показывать использование процессора и памяти для рабочих пространств и сеансов терминала в верхней панели",
		keywords: [
			"features",
			"resource",
			"monitor",
			"cpu",
			"memory",
			"ram",
			"usage",
			"performance",
			"process",
			"terminal",
			"поведение",
			"ресурсы",
			"монитор",
			"процессор",
			"память",
			"озу",
			"использование",
			"производительность",
			"процесс",
			"терминал",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_WORKTREE_LOCATION,
		section: "git",
		title: "Расположение worktree",
		description:
			"Базовый каталог на уровне пользователя, где создаются новые worktree",
		keywords: [
			"git",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"base",
			"default",
			"гит",
			"расположение",
			"каталог",
			"путь",
			"папка",
			"хранилище",
			"базовый",
			"по умолчанию",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_OPEN_LINKS_IN_APP,
		section: "behavior",
		title: "Открывать ссылки во встроенном браузере",
		description:
			"Открывать ссылки из чата и терминала во встроенном браузере вместо браузера по умолчанию",
		keywords: [
			"browser",
			"links",
			"in-app",
			"external",
			"open",
			"chat",
			"terminal",
			"url",
			"браузер",
			"ссылки",
			"встроенный",
			"внешний",
			"открыть",
			"чат",
			"терминал",
			"адрес",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_ENABLED,
		section: "agents",
		title: "Включённые агенты",
		description:
			"Управление тем, какие агенты появляются в запуске рабочих пространств",
		keywords: [
			"agents",
			"enabled",
			"launcher",
			"dropdown",
			"visible",
			"show",
			"hide",
			"rox chat",
			"claude",
			"codex",
			"pi",
			"агенты",
			"включённые",
			"запуск",
			"выпадающий список",
			"видимые",
			"показать",
			"скрыть",
			"рабочее пространство",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_COMMANDS,
		section: "agents",
		title: "Команды агентов",
		description: "Настройка команд запуска с приглашением и без приглашения",
		keywords: [
			"agents",
			"commands",
			"prompt command",
			"terminal",
			"claude",
			"codex",
			"gemini",
			"opencode",
			"pi",
			"copilot",
			"cursor",
			"агенты",
			"команды",
			"команда запроса",
			"терминал",
			"запуск",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_TASK_PROMPTS,
		section: "agents",
		title: "Шаблоны промптов задач",
		description: "Настройка шаблонов промптов задач для запуска агентов",
		keywords: [
			"agents",
			"task prompt",
			"template",
			"variables",
			"prompt",
			"task",
			"rox chat",
			"launch",
			"агенты",
			"промпт задачи",
			"шаблон",
			"переменные",
			"промпт",
			"задача",
			"запуск",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_PRESETS,
		section: "terminal",
		title: "Пресеты терминала",
		description: "Управление пресетами терминала",
		keywords: [
			"terminal",
			"preset",
			"presets",
			"commands",
			"agent",
			"launch",
			"default",
			"startup",
			"config",
			"shell",
			"run",
			"терминал",
			"пресет",
			"пресеты",
			"команды",
			"агент",
			"запуск",
			"по умолчанию",
			"конфигурация",
			"оболочка",
			"запустить",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_QUICK_ADD,
		section: "terminal",
		title: "Шаблоны быстрого добавления",
		description: "Предварительно настроенные пресеты терминала",
		keywords: [
			"terminal",
			"quick",
			"add",
			"template",
			"claude",
			"codex",
			"gemini",
			"cursor",
			"opencode",
			"pi",
			"ai",
			"assistant",
			"терминал",
			"быстрое",
			"добавить",
			"шаблон",
			"пресет",
			"ассистент",
			"ии",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_SESSIONS,
		section: "terminal",
		title: "Служба терминала",
		description: "Управление службой терминала и активными сеансами",
		keywords: [
			"terminal",
			"sessions",
			"active",
			"running",
			"kill",
			"terminate",
			"process",
			"stop",
			"manage",
			"pty",
			"daemon",
			"pty daemon",
			"supervisor",
			"restart daemon",
			"update daemon",
			"background",
			"терминал",
			"сеансы",
			"активные",
			"запущенные",
			"завершить",
			"процесс",
			"остановить",
			"управление",
			"служба",
			"демон",
			"супервизор",
			"перезапуск службы",
			"фоновый процесс",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_LINK_BEHAVIOR,
		section: "terminal",
		title: "Поведение ссылок",
		description: "Как открывать ссылки из терминала",
		keywords: [
			"terminal",
			"link",
			"click",
			"open",
			"external",
			"editor",
			"file",
			"url",
			"path",
			"cmd",
			"ctrl",
			"browser",
			"терминал",
			"ссылка",
			"клик",
			"открыть",
			"внешний",
			"редактор",
			"файл",
			"адрес",
			"путь",
			"браузер",
		],
	},
	{
		id: SETTING_ITEM_ID.LINKS_FILE,
		section: "links",
		title: "Файловые ссылки",
		description:
			"Как открываются пути к файлам при клике в терминалах, чате и задачах",
		keywords: [
			"links",
			"file",
			"click",
			"cmd",
			"ctrl",
			"shift",
			"meta",
			"pane",
			"editor",
			"external",
			"open",
			"terminal",
			"chat",
			"markdown",
			"behavior",
			"ссылки",
			"файл",
			"клик",
			"панель",
			"редактор",
			"внешний",
			"открыть",
			"терминал",
			"чат",
			"поведение",
		],
	},
	{
		id: SETTING_ITEM_ID.LINKS_URL,
		section: "links",
		title: "URL-ссылки",
		description: "Как открываются URL при клике в терминалах, чате и задачах",
		keywords: [
			"links",
			"url",
			"link",
			"click",
			"cmd",
			"ctrl",
			"shift",
			"meta",
			"browser",
			"in-app",
			"system",
			"external",
			"open",
			"terminal",
			"chat",
			"markdown",
			"behavior",
			"ссылки",
			"адрес",
			"ссылка",
			"клик",
			"браузер",
			"встроенный",
			"системный",
			"внешний",
			"открыть",
			"терминал",
			"чат",
			"поведение",
		],
	},
	{
		id: SETTING_ITEM_ID.LINKS_SIDEBAR_FILE,
		section: "links",
		title: "Строки файлов в боковой панели",
		description:
			"Как открываются строки файлов в дереве файлов, списке изменений и заголовке различий при клике",
		keywords: [
			"links",
			"sidebar",
			"file tree",
			"changes",
			"diff",
			"file",
			"click",
			"cmd",
			"ctrl",
			"shift",
			"meta",
			"new tab",
			"editor",
			"external",
			"open",
			"select",
			"behavior",
			"ссылки",
			"боковая панель",
			"дерево файлов",
			"изменения",
			"различия",
			"файл",
			"клик",
			"новая вкладка",
			"редактор",
			"внешний",
			"открыть",
			"выбрать",
			"поведение",
		],
	},
	{
		id: SETTING_ITEM_ID.PUBLIC_SHARES,
		section: "shares",
		title: "Публичные ссылки",
		description:
			"Просмотр, копирование и отзыв публичных ссылок на чаты и артефакты",
		keywords: [
			"share",
			"shares",
			"sharing",
			"public",
			"link",
			"links",
			"chat",
			"artifact",
			"copy",
			"revoke",
			"snapshot",
			"ссылка",
			"ссылки",
			"публичные",
			"поделиться",
			"шаринг",
			"чат",
			"артефакт",
			"копировать",
			"отозвать",
			"снапшот",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_ROX,
		section: "models",
		title: "Модель ROX R1",
		description: "Бесплатная модель Rox по умолчанию без настройки",
		keywords: [
			"models",
			"rox",
			"rox-1",
			"r1",
			"free",
			"default",
			"модели",
			"бесплатная",
			"по умолчанию",
			"без настройки",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_ANTHROPIC,
		section: "models",
		title: "Авторизация модели Anthropic",
		description:
			"Подключите Anthropic для именования рабочих пространств и задач малых моделей",
		keywords: [
			"models",
			"anthropic",
			"claude",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
			"модели",
			"авторизация",
			"ключ api",
			"именование рабочих пространств",
			"автоматическое имя",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_OPENAI,
		section: "models",
		title: "Авторизация модели OpenAI",
		description: "Подключите OpenAI для поддерживаемых задач моделей",
		keywords: [
			"models",
			"openai",
			"gpt",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
			"модели",
			"авторизация",
			"ключ api",
			"именование рабочих пространств",
			"автоматическое имя",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_GROQ,
		section: "models",
		title: "Ключ API Groq",
		description: "Добавьте ключ Groq для запуска моделей Groq",
		keywords: [
			"models",
			"groq",
			"api key",
			"auth",
			"llama",
			"модели",
			"ключ api",
			"авторизация",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_GOOGLE,
		section: "models",
		title: "Ключ API Google Gemini",
		description: "Добавьте ключ Google Gemini для моделей Gemini",
		keywords: [
			"models",
			"google",
			"gemini",
			"api key",
			"auth",
			"модели",
			"ключ api",
			"авторизация",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_DEEPSEEK,
		section: "models",
		title: "Ключ API DeepSeek",
		description: "Добавьте ключ DeepSeek для моделей DeepSeek",
		keywords: [
			"models",
			"deepseek",
			"api key",
			"auth",
			"reasoner",
			"модели",
			"ключ api",
			"авторизация",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_CUSTOM,
		section: "models",
		title: "Свой провайдер",
		description:
			"Подключите любой OpenAI-совместимый эндпоинт по Base URL и ключу",
		keywords: [
			"models",
			"custom",
			"openai compatible",
			"base url",
			"api key",
			"endpoint",
			"свой провайдер",
			"кастомный",
			"совместимый",
			"модели",
			"ключ api",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.EXPERIMENTAL_TEAM_OS,
		section: "experimental",
		title: "Экспериментальные функции",
		description:
			"Переключатели и диагностика экспериментальных функций Agent-Native, шаблонов, Liveblocks, LiveKit, Huly и объединённых процессов",
		keywords: [
			"experimental",
			"experiments",
			"feature flags",
			"toggles",
			"agent-native",
			"agent native",
			"templates",
			"liveblocks",
			"livekit",
			"huly",
			"collaboration",
			"rooms",
			"voice",
			"project os",
			"customer call",
			"roadmap",
			"source marketplace",
			"agent participant",
			"экспериментальное",
			"эксперименты",
			"флаги",
			"тоглы",
			"агенты",
			"шаблоны",
			"коллаборация",
			"комнаты",
			"голос",
			"проект",
			"роадмап",
		],
	},
	{
		id: SETTING_ITEM_ID.EXPERIMENTAL_V1_MIGRATION,
		section: "experimental",
		title: "Миграция с V1 на V2",
		description: "Повторный запуск миграции данных с V1 на V2",
		keywords: [
			"experimental",
			"migration",
			"migrate",
			"rerun",
			"retry",
			"recover",
			"v1",
			"v2",
			"projects",
			"workspaces",
			"экспериментальное",
			"миграция",
			"мигрировать",
			"повторный запуск",
			"повторить",
			"восстановить",
			"проекты",
			"рабочие пространства",
		],
	},
	{
		id: SETTING_ITEM_ID.EXPERIMENTAL_RERUN_ONBOARDING,
		section: "experimental",
		title: "Запустить настройку снова",
		description:
			"Снова открыть руководство по настройке для подключения агентов и добавления проектов",
		keywords: [
			"experimental",
			"onboarding",
			"setup",
			"guide",
			"rerun",
			"re-run",
			"restart",
			"welcome",
			"getting started",
			"connect",
			"github cli",
			"providers",
			"agents",
			"экспериментальное",
			"онбординг",
			"настройка",
			"руководство",
			"повторный запуск",
			"перезапуск",
			"добро пожаловать",
			"начало работы",
			"подключить",
			"провайдеры",
			"агенты",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_LINEAR,
		section: "integrations",
		title: "Linear",
		description: "Двусторонняя синхронизация задач с Linear",
		keywords: [
			"integrations",
			"linear",
			"issues",
			"tasks",
			"sync",
			"connect",
			"connected",
			"project management",
			"интеграции",
			"задачи",
			"тикеты",
			"синхронизация",
			"подключить",
			"подключено",
			"управление проектами",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_GITHUB,
		section: "integrations",
		title: "GitHub",
		description: "Подключение репозиториев и синхронизация пул-реквестов",
		keywords: [
			"integrations",
			"github",
			"repos",
			"repositories",
			"pull requests",
			"pr",
			"sync",
			"connect",
			"connected",
			"version control",
			"git",
			"интеграции",
			"репозитории",
			"пул-реквесты",
			"запросы на слияние",
			"синхронизация",
			"подключить",
			"подключено",
			"контроль версий",
			"гит",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_SLACK,
		section: "integrations",
		title: "Slack",
		description: "Управление задачами из переписок Slack",
		keywords: [
			"integrations",
			"slack",
			"chat",
			"messages",
			"connect",
			"bot",
			"интеграции",
			"чат",
			"сообщения",
			"подключить",
			"бот",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_TELEGRAM,
		section: "integrations",
		title: "Telegram",
		description: "Запуск агентов через Telegram-бота",
		keywords: [
			"integrations",
			"telegram",
			"bot",
			"chat",
			"messages",
			"connect",
			"интеграции",
			"телеграм",
			"бот",
			"чат",
			"сообщения",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_DISCORD,
		section: "integrations",
		title: "Discord",
		description: "Запуск агентов с Discord-сервера",
		keywords: [
			"integrations",
			"discord",
			"bot",
			"guild",
			"server",
			"channel",
			"connect",
			"интеграции",
			"дискорд",
			"бот",
			"сервер",
			"канал",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_NOTION,
		section: "integrations",
		title: "Notion",
		description: "Синхронизация документов и баз данных Notion",
		keywords: [
			"integrations",
			"notion",
			"docs",
			"documents",
			"database",
			"knowledge",
			"connect",
			"интеграции",
			"документы",
			"база знаний",
			"базы данных",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_OBSIDIAN,
		section: "integrations",
		title: "Obsidian",
		description: "Синхронизация заметок с локальным vault Obsidian",
		keywords: [
			"integrations",
			"obsidian",
			"vault",
			"notes",
			"local rest",
			"knowledge",
			"connect",
			"интеграции",
			"заметки",
			"хранилище",
			"база знаний",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_FIBERY,
		section: "integrations",
		title: "Fibery",
		description: "Подключение рабочего пространства Fibery",
		keywords: [
			"integrations",
			"fibery",
			"tasks",
			"workspace",
			"sync",
			"connect",
			"интеграции",
			"задачи",
			"рабочее пространство",
			"синхронизация",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_LARK,
		section: "integrations",
		title: "Lark",
		description: "Подключение Lark (Feishu) для сообщений и документов",
		keywords: [
			"integrations",
			"lark",
			"feishu",
			"messages",
			"docs",
			"tenant",
			"connect",
			"интеграции",
			"сообщения",
			"документы",
			"подключить",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_NAME,
		section: "project",
		title: "Название проекта",
		description: "Название этого проекта",
		keywords: [
			"project",
			"name",
			"rename",
			"title",
			"label",
			"проект",
			"название",
			"имя",
			"переименовать",
			"заголовок",
			"метка",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_PATH,
		section: "project",
		title: "Путь к репозиторию",
		description: "Путь к файлам этого проекта",
		keywords: [
			"project",
			"path",
			"repository",
			"folder",
			"directory",
			"location",
			"git",
			"repo",
			"root",
			"проект",
			"путь",
			"репозиторий",
			"папка",
			"каталог",
			"расположение",
			"гит",
			"корень",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_SCRIPTS,
		section: "project",
		title: "Скрипты",
		description: "Скрипты настройки, очистки и запуска для рабочих пространств",
		keywords: [
			"project",
			"scripts",
			"setup",
			"teardown",
			"run",
			"bash",
			"shell",
			"automation",
			"hooks",
			"init",
			"initialize",
			"cleanup",
			"onboarding",
			"config",
			"проект",
			"скрипты",
			"настройка",
			"очистка",
			"запуск",
			"оболочка",
			"автоматизация",
			"хуки",
			"инициализация",
			"конфигурация",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_BRANCH_PREFIX,
		section: "project",
		title: "Префикс ветки",
		description: "Переопределить префикс ветки по умолчанию для этого проекта",
		keywords: [
			"project",
			"branch",
			"prefix",
			"naming",
			"git",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
			"override",
			"проект",
			"ветка",
			"префикс",
			"именование",
			"гит",
			"автор",
			"имя пользователя",
			"пользовательский",
			"переопределить",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_WORKTREE_LOCATION,
		section: "project",
		title: "Расположение worktree",
		description: "Переопределить каталог worktree хоста для этого проекта",
		keywords: [
			"project",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"override",
			"проект",
			"расположение",
			"каталог",
			"путь",
			"папка",
			"хранилище",
			"переопределить",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_IMPORT_WORKTREES,
		section: "project",
		title: "Импорт worktree",
		description: "Импорт существующих worktree с диска в Rox",
		keywords: [
			"project",
			"import",
			"worktree",
			"worktrees",
			"workspace",
			"workspaces",
			"external",
			"existing",
			"disk",
			"add",
			"проект",
			"импорт",
			"рабочее пространство",
			"рабочие пространства",
			"внешние",
			"существующие",
			"диск",
			"добавить",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_ENV_VARS,
		section: "project",
		title: "Переменные окружения",
		description:
			"Управление переменными окружения и секретами для облачных песочниц",
		keywords: [
			"environment",
			"variables",
			"secrets",
			"env",
			"cloud",
			"sandbox",
			"окружение",
			"среда",
			"переменные",
			"секреты",
			"облако",
			"облачные",
			"песочница",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_LIST,
		section: "apikeys",
		title: "API-ключи",
		description: "Управление API-ключами для доступа к MCP-серверу",
		keywords: [
			"api",
			"key",
			"keys",
			"mcp",
			"claude",
			"integration",
			"external",
			"access",
			"token",
			"authentication",
			"ключ",
			"ключи",
			"api-ключ",
			"интеграция",
			"внешний",
			"доступ",
			"токен",
			"аутентификация",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_GENERATE,
		section: "apikeys",
		title: "Создать API-ключ",
		description: "Создание новых API-ключей для внешних интеграций",
		keywords: [
			"api",
			"key",
			"generate",
			"create",
			"new",
			"mcp",
			"claude desktop",
			"claude code",
			"ключ",
			"api-ключ",
			"создать",
			"сгенерировать",
			"новый",
			"внешние интеграции",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_FULL_DISK_ACCESS,
		section: "permissions",
		title: "Полный доступ к диску",
		description:
			"Постоянный доступ к Документам, Загрузкам, Рабочему столу и iCloud из сеансов терминала",
		keywords: [
			"permissions",
			"full disk access",
			"fda",
			"files",
			"documents",
			"downloads",
			"desktop",
			"icloud",
			"macos",
			"security",
			"privacy",
			"разрешения",
			"полный доступ к диску",
			"файлы",
			"документы",
			"загрузки",
			"рабочий стол",
			"безопасность",
			"конфиденциальность",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_ACCESSIBILITY,
		section: "permissions",
		title: "Универсальный доступ",
		description:
			"Отправка нажатий клавиш, управление окнами и контроль других приложений",
		keywords: [
			"permissions",
			"accessibility",
			"a11y",
			"keystrokes",
			"window management",
			"macos",
			"security",
			"privacy",
			"trusted",
			"разрешения",
			"универсальный доступ",
			"доступность",
			"нажатия клавиш",
			"управление окнами",
			"безопасность",
			"конфиденциальность",
			"доверенное",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_MICROPHONE,
		section: "permissions",
		title: "Микрофон",
		description:
			"Использование голосовой транскрипции и функций «нажми и говори»",
		keywords: [
			"permissions",
			"microphone",
			"mic",
			"voice",
			"transcription",
			"audio",
			"recording",
			"push to talk",
			"codex",
			"privacy",
			"разрешения",
			"микрофон",
			"голос",
			"транскрипция",
			"аудио",
			"запись",
			"нажми и говори",
			"конфиденциальность",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_APPLE_EVENTS,
		section: "permissions",
		title: "Автоматизация",
		description:
			"Запуск команд терминала и взаимодействие с другими приложениями",
		keywords: [
			"permissions",
			"automation",
			"apple events",
			"applescript",
			"macos",
			"security",
			"privacy",
			"system events",
			"разрешения",
			"автоматизация",
			"события apple",
			"безопасность",
			"конфиденциальность",
			"системные события",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_LOCAL_NETWORK,
		section: "permissions",
		title: "Локальная сеть",
		description: "Обнаружение и подключение к серверам разработки в вашей сети",
		keywords: [
			"permissions",
			"local network",
			"bonjour",
			"mdns",
			"macos",
			"security",
			"privacy",
			"development servers",
			"разрешения",
			"локальная сеть",
			"безопасность",
			"конфиденциальность",
			"серверы разработки",
			"сеть",
		],
	},
	{
		id: SETTING_ITEM_ID.SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY,
		section: "security",
		title:
			"Разрешить удалённым рабочим пространствам доступ к этому устройству через реле",
		description:
			"Управляет тем, могут ли удалённые рабочие пространства достигать вашего локального хост-сервиса через реле Rox",
		keywords: [
			"security",
			"relay",
			"remote",
			"workspace",
			"expose",
			"lockdown",
			"network",
			"inbound",
			"host service",
			"tunnel",
			"attack surface",
			"безопасность",
			"реле",
			"удалённый",
			"рабочее пространство",
			"открыть доступ",
			"блокировка",
			"сеть",
			"входящий",
			"хост-сервис",
			"туннель",
			"поверхность атаки",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_MEMBERS,
		section: "hosts",
		title: "Участники хоста",
		description:
			"Просмотр того, у кого есть доступ к хосту в вашей организации",
		keywords: [
			"host",
			"hosts",
			"member",
			"members",
			"access",
			"team",
			"share",
			"machine",
			"device",
			"хост",
			"хосты",
			"участник",
			"участники",
			"доступ",
			"команда",
			"поделиться",
			"машина",
			"устройство",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_WORKTREE_LOCATION,
		section: "hosts",
		title: "Расположение worktree",
		description:
			"Расположение по умолчанию для новых рабочих пространств worktree на этом хосте",
		keywords: [
			"host",
			"hosts",
			"worktree",
			"worktrees",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"default",
			"хост",
			"хосты",
			"расположение",
			"каталог",
			"путь",
			"папка",
			"хранилище",
			"по умолчанию",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_INVITE_MEMBER,
		section: "hosts",
		title: "Предоставить доступ к хосту",
		description: "Добавление участника организации к хосту",
		keywords: [
			"host",
			"hosts",
			"invite",
			"add",
			"grant",
			"member",
			"access",
			"share",
			"хост",
			"хосты",
			"пригласить",
			"добавить",
			"предоставить",
			"участник",
			"доступ",
			"поделиться",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_MEMBER_ROLE,
		section: "hosts",
		title: "Роль участника хоста",
		description: "Изменение роли участника на хосте (владелец или участник)",
		keywords: [
			"host",
			"hosts",
			"role",
			"owner",
			"member",
			"permission",
			"admin",
			"хост",
			"хосты",
			"роль",
			"владелец",
			"участник",
			"право",
			"администратор",
		],
	},
];

export function searchSettings(query: string): SettingsItem[] {
	return matchSettings(query, SETTINGS_ITEMS);
}

export function getSettingsItem(itemId: SettingItemId): SettingsItem | null {
	return SETTINGS_ITEMS.find((item) => item.id === itemId) ?? null;
}

export function getMatchCountBySection(
	query: string,
): Partial<Record<SettingsSection, number>> {
	const matches = searchSettings(query);
	const counts: Partial<Record<SettingsSection, number>> = {};

	for (const item of matches) {
		counts[item.section] = (counts[item.section] || 0) + 1;
	}

	return counts;
}

export function getMatchingItemsForSection(
	query: string,
	section: SettingsSection,
): SettingsItem[] {
	return searchSettings(query).filter((item) => item.section === section);
}

export function isItemVisible(
	itemId: SettingItemId,
	visibleItems: SettingItemId[] | null | undefined,
): boolean {
	return !visibleItems || visibleItems.includes(itemId);
}

/**
 * Items in `section` that are allowed for the active v1/v2 variant and
 * (if a search query is provided) also match the query. Returns an array
 * suitable for passing to `isItemVisible` at the leaf — never `null`, so
 * variant-hidden items are always excluded.
 */
export function getVisibleItemsForSection(params: {
	section: SettingsSection;
	searchQuery: string;
	isV2: boolean;
}): SettingItemId[] {
	const { section, searchQuery, isV2 } = params;
	const matched = searchQuery.trim()
		? getMatchingItemsForSection(searchQuery, section)
		: SETTINGS_ITEMS.filter((item) => item.section === section);
	return matched
		.filter((item) => isItemAllowedForVariant(item.id, isV2))
		.map((item) => item.id);
}

/**
 * Like `getMatchCountBySection`, but excludes items that are hidden by the
 * active v1/v2 variant. Used by the sidebar so search counts and section
 * visibility agree.
 */
export function getVisibleMatchCountBySection(
	query: string,
	isV2: boolean,
): Partial<Record<SettingsSection, number>> {
	const matches = searchSettings(query).filter((item) =>
		isItemAllowedForVariant(item.id, isV2),
	);
	const counts: Partial<Record<SettingsSection, number>> = {};
	for (const item of matches) {
		counts[item.section] = (counts[item.section] || 0) + 1;
	}
	return counts;
}

/**
 * Sections that contain at least one item allowed for the active variant.
 * Sections with no allowed items (e.g. `git` in v2, `links` in v1) should
 * be hidden from the sidebar entirely.
 */
export function getAllowedSectionsForVariant(
	isV2: boolean,
): Set<SettingsSection> {
	const sections = new Set<SettingsSection>();
	for (const item of SETTINGS_ITEMS) {
		if (isItemAllowedForVariant(item.id, isV2)) sections.add(item.section);
	}
	return sections;
}
